[package]
name = "braxon"
version = "1.0.6"
description = "BRAXON — ABS Hydraulic Diagnostics Platform"
authors = ["Gabhy Rodrich KIBA"]
license = ""
repository = ""
default-run = "braxon"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5", features = [ "protocol-all", "dialog-all", "fs-all", "path-all", "shell-open", "updater", "process-relaunch", "window-close", "window-hide", "window-maximize", "window-minimize", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
serialport = "4.2"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.30", features = ["bundled"] }
tokio-postgres = { version = "0.7", features = [] }
sha2 = "0.10"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
