<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>SC F2-EVO</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="ElectronikSistem">
      <HintPath>..\..\..\..\..\..\..\..\..\..\GABHYK~1\AppData\Local\Temp\claude\c--Users-Gabhy-Kiba-OneDrive---Reman-By-ADLC-Documents-KIBA-GABHY-braxon-tauri\6746725a-ba0f-4754-b16f-d726a3703064\scratchpad\f2evo\ElectronikSistem.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web.Services" />
  </ItemGroup>
</Project>